services:
  # for development purposes
  dev:
    build: .
    volumes:
        - ./:/code
        - ./data:/data
    environment:
      - KBC_DATADIR=./data

  test:
    # Use to run flake8 and unittests checks
    build: .
    volumes:
      - ./:/code
      - ./data:/data
    environment:
      - KBC_DATADIR=./data
    command:
      - /bin/sh
      - /code/scripts/build_n_test.sh
    links:
      - mock-server
    depends_on:
      - mock-server

  functional-tests:
    # Run examples against mock server
    build: .
    volumes:
      - ./:/code
      - ./data:/data
    command: python /code/docs/examples/run_examples.py
    links:
      - mock-server

  mock-server:
    container_name: mock-server
    image: quay.io/keboola/ex-generic-mock-server
    tty: true
    stdin_open: true
    ports:
      - "8888:80"
    volumes:
      - ./docs/examples:/examples/
      - ./docs/legacy_v1_examples:/legacy_examples/
    environment:
      - KBC_EXAMPLES_DIR=/examples/